<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AssemblyName>RocoPilot.Installer.Core</AssemblyName>
    <RootNamespace>RocoPilot.Installer.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\RocoPilot.Input\native\win-x64\interception.dll" Link="interception.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>