<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RocoPilot.Input\RocoPilot.Input.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.12" />
  </ItemGroup>

</Project>
